### ISSUE TITLE
Wöchentlicher Cronjob für Backup-Zwecke

### ISSUE THREAD

**Issue by mritzmann** [dnszensur/api.dnszensur.ch#4]
1x Wöchentlich (Vorschlag: Sonntag) einen Cronjob der ein Backup der JSON-Files erstellt.

**Comment by cmllr** [comment]
obnam ist ganz schnieke, wenns um nicht-binäre Dateien geht!

**Comment by nebucaz** [comment]
Warum nicht permanent in IPDB speichern? 
--> https://ipdb.io
